Agency/telemetry: add `unregistered` error
openmobilityfoundation/mobility-data-specification pull request #565
Opened 2020-08-24 12:14 UTC by Retzoh

### Is your feature request related to a problem? Please describe.

As an agency, when receiving a batch of telemetry data including unregistered devices, there is currently no official way to let the provider know why the corresponding telemetries were rejected. This makes it complicated for the provider to automate the detection and resolution of this problem.

### Describe the solution you'd like

Adapt the `unregistered` error existing in the Agency/event endpoint to Agency/telemetry.

### Is this a breaking change

No, not breaking : we are just adding a new error type. 

### Impacted Spec

For which spec is this feature being requested?

 * `agency`

### Describe alternatives you've considered

The current workaround we are using is to return a bad_param error on parameter `device_id`, Listing the unregistered ids in the error description: `A validation error occured. Unregistered devices: UUID1, UUID2, etc.`.

### Additional context

Add any other context or screenshots about the feature request here.

2020-08-24 12:23 UTC, viestat commented
Really looking forward for this!
It makes everything much simpler. As the consumer of the `Agency` endpoints it helps enormously to not only know what made a batch fail but specifically which vehicles are not registered. Then it is possible to trigger a register request for any vehicle present in that error as soon as this error is received.

2020-08-24 17:11 UTC, karcass commented
This is already in the mds-core implementation.  Will add to spec.

2020-09-30 18:32 UTC, schnuerle commented
We will be talking about this on the Working Group call tomorrow: https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2020.10.01-(Joint-Working-Group-City-Services)

2020-10-01 17:18 UTC, schnuerle commented
From the call today @karcass will double check but it looks good and can be merged to `dev`.

2020-10-01 18:16 UTC, karcass requested changes
Ah, I see where this diverges from the mds-core implementation.  `unregistered` shows up in the `failures` field and does not necessarily force a 400.  What will show up in that case is the `failures` array will contain one entry per failure of the form

```
device_id ${telemetry.device_id}: not found
```

So I would change the PR to describe this as a possible `failure` entry.  A bad device should not prevent the receipt of valid telemetry data.

What do you think about this counter-proposal?

2020-11-18 02:31 UTC, schnuerle commented
@karcass are you waiting on @Retzoh to reply here on your counter proposal? @Retzoh what do you think so we can merge this PR?

2020-11-18 22:11 UTC, karcass commented
@schnuerle Yes, I'm interested in what @Retzoh thinks about my counter.

2020-11-23 09:44 UTC, Retzoh commented
Hi @karcass , sorry, I missed the initial ping.

I think it is dangerous to return a success code and rely on text-processing of the response payload to handle any errors.
To me, any error should be really straightforward.

Additionally, it seems more robust to me to just reject a invalid batch of telemetries until it is valid and pick-up the ingestion from there, rather than moving on and rely on tracking specific errors until resolved. With the second solution, it seems too easy both for the provider and the city to forget the errors and never handle them.

It would be interesting to have some feedback from providers on this. @viestat do you have an opinion ?

2020-11-30 21:02 UTC, schnuerle commented
Tagging some more providers who may have a technical opinion on this: @dirkdk @bhandzo.

2020-12-08 20:56 UTC, schnuerle commented
Do you think you can reach some consensus on this here in the GitHub PR in the next week so these changes can be added to the 1.1.0 release?

2020-12-10 16:58 UTC, karcass commented
We can add a response field called e.g. `unknown_device_ids` which would be an array of device_ids that are not in the DB.  Agree that parsing text responses is not good practice.

2020-12-11 07:46 UTC, dirkdk commented
so the 2 alternatives are:
1. return 400 HTTP error code and error with key `failures` that contains an array of unregistered vehicle ids
2. return 200 HTTP success code but still a `failures` key that contains an array of unregistered vehicle ids. 

For 1), for me it is implied that no data, even from already registered vehicles is processed
For 2), for me it is implied that correct data from registered vehicles is indeed processed but not for unregistered vehicles

IMHO, the solutions are very similar. I would opt for 1), as it is more explicit and its is clear that no data at all is processed and the client will need to correct their mistake and then retry.

2020-12-14 09:05 UTC, viestat commented
In my opinion as the consumer of the `Agency` endpoints,  I agree with what @Retzoh says about having to rely on the text response to identify errors.

If the endpoint takes batches as a whole it really does not make any sense to me to then treat individual items in the batch selectively. Either **all** the items that make up a batch are correct (and registered) in orderer to be processed or the batch is rejected and the reasons why it was rejected are made evident via the appropriate error (essentially what @dirkdk [proposed above as option #1](https://github.com/openmobilityfoundation/mobility-data-specification/pull/565#issuecomment-743032938)).

Doing this relieves the load on both sides (the consumer and the provider of the API) as it enables for a simpler retry flow and error handling.

2020-12-14 19:10 UTC, karcass approved these changes
Sorry, I misread this diff originally.  Is fine!

2020-12-14 19:10 UTC, schnuerle approved these changes
Looks good thanks for the conversations and concensus.

2020-12-14 19:10 UTC, merged